CREATE TABLE Users(
    ID IDENTITY NOT NULL,
    LOGIN TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    PRIMARY KEY (ID));

CREATE TABLE Articles(
    ID IDENTITY NOT NULL,
    NAME TEXT NOT NULL,
    TOPIC TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    AUTHOR INTEGER NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (AUTHOR)
            REFERENCES Users (ID),
    PRIMARY KEY (ID));

CREATE TABLE Comments(
    ID IDENTITY NOT NULL,
    AUTHOR INTEGER NOT NULL,
    ARTICLE INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR)
            REFERENCES Users (ID),
    CONSTRAINT FK_ARTICLE FOREIGN KEY (ARTICLE)
            REFERENCES Articles (ID),
    PRIMARY KEY (ID));
